app_seller_dashboard:
    path: /seller/dashboard
    methods: [GET, POST]
    defaults:
        _controller: 'App\Controller\SellerController::dashboard'

### SECURITY ###
sylius_seller_login:
    path: /seller/login
    methods: [GET]
    defaults:
        _controller: sylius.controller.security:loginAction
        _sylius:
            template: "login.html.twig"
            logged_in_route: sylius_seller_account_dashboard

sylius_seller_login_check:
    path: /seller/login-check
    methods: [POST]
    defaults:
        _controller: sylius.controller.security:checkAction

sylius_seller_logout:
    path: /seller/logout
    methods: [GET]

sylius_seller_register:
    path: /seller/register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer:createAction
        _sylius:
            template: "@SyliusShop/register.html.twig"
            form: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType
            event: register
            redirect:
                route: sylius_seller_account_dashboard
            flash: sylius.customer.register

sylius_seller_register_after_checkout:
    path: /seller/register-after-checkout/{tokenValue}
    methods: [GET]
    defaults:
        _controller: sylius.controller.customer:createAction
        _sylius:
            form: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType
            factory:
                method: ['expr:service("sylius.factory.customer_after_checkout")', 'createAfterCheckout']
                arguments:
                    - 'expr:service("sylius.repository.order").findOneByTokenValue($tokenValue)'
            template: "@SyliusShop/register.html.twig"
            event: register
            redirect:
                route: sylius_seller_account_dashboard
            flash: sylius.customer.register

sylius_seller_request_password_reset_token:
    path: /seller/forgotten-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.seller_user:requestPasswordResetTokenAction
        _sylius:
            template: "@SyliusShop/Account/requestPasswordReset.html.twig"
            redirect: sylius_seller_login

sylius_seller_password_reset:
    path: /seller/forgotten-password/{token}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.seller_user:resetPasswordAction
        _sylius:
            template: "@SyliusShop/Account/resetPassword.html.twig"
            redirect: sylius_seller_login
### \SECURITY ###
