# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_US

services:
    # Default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services
        autowire: true

        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

        # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work
        public: false

    # Makes classes in src/ available to be used as services;
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Fixture,Kernel.php}'

    # Controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    sylius.seller_user_provider.username_based:
        class: Sylius\Bundle\UserBundle\Provider\UsernameProvider
        autowire: false
        autoconfigure: false
        public: false
        parent: 'sylius.seller_user_provider'

    sylius.seller_user_provider:
        class: Sylius\Bundle\UserBundle\Provider\AbstractUserProvider
        abstract: true
        lazy: true
        arguments:
            - 'App\Entity\User\SellerUser'
            - '@sylius.repository.seller_user'
            - '@sylius.canonicalizer'

    sylius.handler.seller_user_logout:
        class: App\EventListener\SellerUserLogoutHandler
        arguments:
            - '@security.http_utils'
            - '/'
            - '@sylius.context.channel.composite'
            - '@sylius.storage.cart_session'

    app.fixture.seller_user:
        autowire: false
        class: App\Fixture\SellerUserFixture
        arguments:
            - '@sylius.manager.seller_user'
            - '@app.fixture.example_factory.seller_user'
        tags:
            - {name: sylius_fixtures.fixture}

    app.fixture.example_factory.seller_user:
        autowire: false
        class: App\Fixture\Factory\SellerUserExampleFactory
        arguments:
            - '@sylius.factory.seller_user'
